# .github/workflows/python-publish.yml
name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  release:
    types: [created]

jobs:
  check-codecov-token:
    runs-on: ubuntu-latest
    steps:
      - name: Check CODECOV_TOKEN
        run: echo "CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}"

  call-publish:
    uses: casangi/toolviper/.github/workflows/python-publish-template.yml@main
    with:
      pypi-url: "https://pypi.org/project/toolviper"
    secrets: inherit