name: Python Testing Integration

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.rst'

# For testing the workflow.
# on:
#     push:
#         paths-ignore:
#         - '**.md'
#         - '**.rst'

jobs:
  test:
    uses: casangi/toolviper/.github/workflows/python-testing-integration-template.yml@471-fix-data-type-used-in-tests-with-toolviper-download
