# .github/workflows/python-testing-macos.yml
name: MacOS Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  call-testing-macos:
    uses: nrao/gh-actions-templates-public/.github/workflows/python-testing-macos-template.yml@2-ipynb-workflow-is-getting-stuck