name: MacOS

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  build:
    name: macos (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
        python-version: ["3.9", "3.10","3.11","3.12"]
    steps:
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: xradiotest
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      
      - uses: actions/checkout@v4
      
      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          
      - name: Test with pytest
        run: pytest
