name: Python Testing Integration

# on:
#   pull_request:
#     branches: [main]

on:
    push:
        paths-ignore:
        - '**.md'
        - '**.rst'

jobs:
  test:
    uses: ${{ github.repository_owner }}/toolviper/.github/workflows/python-testing-integration-template.yml@main