# .github/workflows/python-testing-linux.yml
name: "Python Linux testing (from template)"

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  call-testing-linux:
    uses: casangi/toolviper/.github/workflows/python-testing-linux-template.yml@main