name: Python Testing Integration Template

on:
  workflow_call:

jobs:
  test-all:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout calling repository (PR version)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install core test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Print Statements
        run: |
           echo "1 github.repository_owner=${{ github.repository_owner }}"
           echo "2 github.repository=${{ github.repository }}"
           echo "3 ${{ github.repository_owner }}/toolviper"
           echo "Are they equal:"
           echo "${{ github.repository }}" == "${{ github.repository_owner }}/toolviper"
           if [ "${{ github.repository }}" = "${{ github.repository_owner }}/toolviper" ]; then
             echo "Yes"
           else
             echo "No"
           fi

      # 1. ToolVIPER
      - name: Clone and install ToolVIPER (main)
        if: github.repository != '${{ github.repository_owner }}/toolviper'
        run: |
          git clone https://github.com/${{ github.repository_owner }}/toolviper.git
          pip install -e toolviper

      # 2. XRADIO
      - name: Clone and install XRADIO (main)
        if: github.repository != '${{ github.repository_owner }}/xradio'
        run: |
          git clone https://github.com/${{ github.repository_owner }}/xradio.git
          pip install -e xradio

      # 3. GraphVIPER
      - name: Clone and install GraphVIPER (main)
        if: github.repository != '${{ github.repository_owner }}/graphviper'
        run: |
          git clone https://github.com/${{ github.repository_owner }}/graphviper.git
          pip install -e graphviper

      # 4. AstroVIPER
      - name: Clone and install AstroVIPER (main)
        if: github.repository != '${{ github.repository_owner }}/astroviper'
        run: |
          git clone https://github.com/${{ github.repository_owner }}/astroviper.git
          pip install -e astroviper

      # 5. Run tests
      - name: Run ToolVIPER tests
        run: |
          if [ "${{ github.repository }}" = "${{ github.repository_owner }}/toolviper" ]; then
            pytest tests
          else
            pytest toolviper/tests
          fi

      # - name: Run XRADIO tests
      #   run: |
      #     if [ "${{ github.repository }}" = "${{ github.repository_owner }}/xradio" ]; then
      #       pytest tests
      #     else
      #       pytest xradio/tests
      #     fi

      - name: Run GraphVIPER tests
        run: |
          if [ "${{ github.repository }}" = "${{ github.repository_owner }}/graphviper" ]; then
            pytest tests
          else
            pytest graphviper/tests
          fi

      - name: Run AstroVIPER tests
        run: |
          if [ "${{ github.repository }}" = "${{ github.repository_owner }}/astroviper" ]; then
            pytest tests
          else
            pytest astroviper/tests
          fi

