name: Python Testing Integration Template

on:
  workflow_call:

jobs:
  test-all:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout calling repository (PR version)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install core test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # For debugging
      # - name: Print Statements
      #   run: |
      #      echo "1 github.repository_owner=casangi"
      #      echo "2 github.repository=${{ github.repository }}"
      #      echo "3 casangi/toolviper"
      
      # 1. If no ToolVIPER install from main
      - name: Clone and install ToolVIPER (main)
        if: github.repository != 'casangi/toolviper'
        run: |
          git clone https://github.com/casangi/toolviper.git
          pip install -e toolviper

      # 2. If no XRADIO install from main
      - name: Clone and install XRADIO (main)
        if: github.repository != 'casangi/xradio'
        run: |
          git clone https://github.com/casangi/xradio.git
          pip install -e xradio

      # 3. If no GraphVIPER install from main
      - name: Clone and install GraphVIPER (main)
        if: github.repository != 'casangi/graphviper'
        run: |
          git clone https://github.com/casangi/graphviper.git
          pip install -e graphviper

      # 4. If no AstroVIPER install from main
      - name: Clone and install AstroVIPER (main)
        if: github.repository != 'casangi/astroviper'
        run: |
          git clone https://github.com/casangi/astroviper.git
          pip install -e astroviper

      - name: Install PR Package
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .

      # 5. Run tests
      - name: Run ToolVIPER tests
        run: |
          if [ "${{ github.repository }}" = "casangi/toolviper" ]; then
            pytest tests
            pytest tests_integration
          else
            pytest toolviper/tests
            pytest toolviper/tests_integration
          fi

      - name: Run XRADIO tests
        run: |
          if [ "${{ github.repository }}" = "casangi/xradio" ]; then
            pytest tests
          else
            pytest xradio/tests
          fi

      - name: Run GraphVIPER tests
        run: |
          if [ "${{ github.repository }}" = "casangi/graphviper" ]; then
            pytest tests
          else
            pytest graphviper/tests
          fi

      - name: Run AstroVIPER tests
        run: |
          if [ "${{ github.repository }}" = "casangi/astroviper" ]; then
            pytest tests
          else
            pytest astroviper/tests
          fi

