# .github/workflows/run-ipynb.yml
name: ipynb Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  call-testing-ipynb:
    uses: nrao/gh-actions-templates-public/.github/workflows/run-ipynb-template.yml@2-ipynb-workflow-is-getting-stuck
    secrets: inherit