# .github/workflows/python-testing-linux.yml
name: ipynb Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  # check-codecov-token:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check CODECOV_TOKEN
  #       run: echo "CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}"

  call-testing-linux:
    uses: casangi/toolviper/.github/workflows/run-ipynb-template.yml@main
    secrets: inherit