name: ipynb Tests

on:
  workflow_call:
    
jobs:
  build:
    name: ipynb (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    steps:
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: false
        activate-environment: test
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge

    - run: conda install graphviz 

    - uses: actions/checkout@v4

    - name: Install dependencies with pip
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        pip install jupyterlab, matplotlib

    - name: Run Jupyter notebooks
      run: |
       ORIGINAL_DIR=$(pwd)
       for notebook in $(find docs -name '*.ipynb'); do
        echo "Running notebook: $notebook"
        # ls -al
        # pwd
        # jupyter nbconvert --to notebook --execute $notebook --output $(basename $notebook) --stdout

        NOTEBOOK_DIR=$(dirname "$notebook")
        NOTEBOOK_FILE=$(basename "$notebook")

        echo "NOTEBOOK_DIR: $NOTEBOOK_DIR, NOTEBOOK_FILE: $NOTEBOOK_FILE"
        echo "Original dir $ORIGINAL_DIR"

        cd "$NOTEBOOK_DIR"

        echo "1 ********************"
        ls -al
        echo "********************"
        python -c 'import toolviper; import os; toolviper.utils.data.download(file="gmrt.ms")'
        echo "2 ********************"
        ls -al
        echo "********************"

        pwd
        jupyter nbconvert --to notebook --execute "$NOTEBOOK_FILE" --output "$NOTEBOOK_FILE" --stdout
        cd "$ORIGINAL_DIR"
       done